services:
  warehouse:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: warehouse
    command: bash script/start.sh
    depends_on:
      - warehouse_db
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    env_file:
      - .env
    networks:
      - warehouse_net

  warehouse_css:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: warehouse_css
    command: bundle exec rails tailwindcss:watch
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
    networks:
      - warehouse_net

  warehouse_db:
    image: "postgres:17"
    container_name: warehouse_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - warehouse_net

volumes:
  postgres_data:
  gem_cache:

networks:
  warehouse_net:
